In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the data
matches_df = pd.read_csv('2024_LoL_esports_match_data_from_OraclesElixir.csv')
grouped = matches_df.groupby('gameid')

In [3]:
grouped.head()

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15
0,10660-10660_game_1,partial,https://lpl.qq.com/es/stats.shtml?bmid=10660,DCup,2023,NaN,0,2024-01-01 05:13:15,1,13.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10660-10660_game_1,partial,https://lpl.qq.com/es/stats.shtml?bmid=10660,DCup,2023,NaN,0,2024-01-01 05:13:15,1,13.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10660-10660_game_1,partial,https://lpl.qq.com/es/stats.shtml?bmid=10660,DCup,2023,NaN,0,2024-01-01 05:13:15,1,13.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10660-10660_game_1,partial,https://lpl.qq.com/es/stats.shtml?bmid=10660,DCup,2023,NaN,0,2024-01-01 05:13:15,1,13.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10660-10660_game_1,partial,https://lpl.qq.com/es/stats.shtml?bmid=10660,DCup,2023,NaN,0,2024-01-01 05:13:15,1,13.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11736,LOLTMNT02_45623,complete,NaN,LCS,2024,Spring,0,2024-02-10 23:44:51,1,14.03,...,128.0,492.0,242.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0
11737,LOLTMNT02_45623,complete,NaN,LCS,2024,Spring,0,2024-02-10 23:44:51,1,14.03,...,103.0,154.0,181.0,-10.0,1.0,1.0,0.0,0.0,0.0,0.0
11738,LOLTMNT02_45623,complete,NaN,LCS,2024,Spring,0,2024-02-10 23:44:51,1,14.03,...,143.0,139.0,-309.0,1.0,0.0,2.0,0.0,0.0,0.0,1.0
11739,LOLTMNT02_45623,complete,NaN,LCS,2024,Spring,0,2024-02-10 23:44:51,1,14.03,...,128.0,654.0,-583.0,-4.0,1.0,2.0,0.0,0.0,0.0,0.0
11740,LOLTMNT02_45623,complete,NaN,LCS,2024,Spring,0,2024-02-10 23:44:51,1,14.03,...,13.0,1293.0,942.0,5.0,2.0,2.0,0.0,0.0,0.0,3.0

In [18]:
transformed_data = []
for name, group in grouped:
    # Get Blue and Red team data
    Blue_team = group[group["side"] == "Blue"]
    Red_team = group[group["side"] == "Red"]

    # Create a dictionary to store the transformed data for this game
    game_data = {
        "teamBlue": Blue_team.iloc[0]["teamname"],
        "teamRed": Red_team.iloc[0]["teamname"],
        "patch": group.iloc[0]["patch"],
        "winner": "Blue" if Blue_team.iloc[0]["result"] == 1 else "Red",
    }

    # Extract champion data for each team
    for i in range(1, 6):
        champ1 = Blue_team[Blue_team["participantid"] == i]["champion"].values[0]
        champ2 = Red_team[Red_team["participantid"] == i + 5]["champion"].values[0]
        game_data[f"Blue_champion_{i}"] = champ1
        game_data[f"Red_champion_{i}"] = champ2

        
            

    # Append the game data to the transformed data list
    transformed_data.append(game_data)


transformed_df = pd.DataFrame(transformed_data)

transformed_df.head()

,teamBlue,teamRed,patch,winner,Blue_champion_1,Red_champion_1,Blue_champion_2,Red_champion_2,Blue_champion_3,Red_champion_3,Blue_champion_4,Red_champion_4,Blue_champion_5,Red_champion_5
0,LNG Esports,Rare Atom,13.24,Red,Aatrox,Rumble,Maokai,Rell,Orianna,LeBlanc,Kalista,Varus,Senna,Renata Glasc
1,LNG Esports,Rare Atom,13.24,Red,Kennen,Jax,Bel'Veth,Jarvan IV,Neeko,LeBlanc,Senna,Kalista,Tahm Kench,Rell
2,LNG Esports,Rare Atom,13.24,Blue,Jax,Aatrox,Bel'Veth,Lee Sin,Neeko,Azir,Caitlyn,Kalista,Lux,Renata Glasc
3,Rare Atom,LNG Esports,13.24,Blue,Rumble,Aatrox,Jarvan IV,Wukong,Tristana,Orianna,Draven,Kalista,Renata Glasc,Senna
4,JD Gaming,Top Esports,13.24,Blue,Renekton,Aatrox,Xin Zhao,Lee Sin,Azir,Orianna,Varus,Lucian,Nautilus,Milio

In [19]:
transformed_df.to_csv("transformed_data.csv", index=False)